<?php

namespace Database\Seeders;

use App\Models\Food;
use App\Models\FoodCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class FoodCatalogSeeder extends Seeder
{
    /**
     * Seed the local food catalog used by nutrition plans.
     */
    public function run(): void
    {
        $categories = [
            ['name' => 'Proteinas', 'slug' => 'proteinas', 'icon' => 'bi-lightning-charge-fill', 'sort_order' => 1],
            ['name' => 'Carbohidratos', 'slug' => 'carbohidratos', 'icon' => 'bi-bar-chart-fill', 'sort_order' => 2],
            ['name' => 'Frutas', 'slug' => 'frutas', 'icon' => 'bi-flower1', 'sort_order' => 3],
            ['name' => 'Verduras', 'slug' => 'verduras', 'icon' => 'bi-leaf-fill', 'sort_order' => 4],
            ['name' => 'Grasas', 'slug' => 'grasas', 'icon' => 'bi-droplet-fill', 'sort_order' => 5],
            ['name' => 'Lacteos', 'slug' => 'lacteos', 'icon' => 'bi-cup-straw', 'sort_order' => 6],
            ['name' => 'Suplementos', 'slug' => 'suplementos', 'icon' => 'bi-capsule', 'sort_order' => 7],
            ['name' => 'Extras', 'slug' => 'extras', 'icon' => 'bi-plus-circle', 'sort_order' => 8],
        ];

        foreach ($categories as $category) {
            FoodCategory::updateOrCreate(
                ['slug' => $category['slug']],
                $category
            );
        }

        $foods = [
            ['category' => 'suplementos', 'name' => 'Proteina whey', 'base_unit' => '1 scoop', 'base_quantity' => 1, 'calories' => 122, 'protein' => 27.70, 'carbohydrates' => .39, 'fat' => 1.25],
            ['category' => 'carbohidratos', 'name' => 'Avena', 'base_unit' => '50 g', 'base_quantity' => 50, 'calories' => 194, 'protein' => 8.44, 'carbohydrates' => 33.14, 'fat' => 3.45],
            ['category' => 'frutas', 'name' => 'Fresas', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 32, 'protein' => .67, 'carbohydrates' => 1.68, 'fat' => .30],
            ['category' => 'frutas', 'name' => 'Platano', 'base_unit' => '130 g', 'base_quantity' => 130, 'calories' => 116, 'protein' => 1.42, 'carbohydrates' => 29.69, 'fat' => .43],
            ['category' => 'extras', 'name' => 'Miel', 'base_unit' => '1 cucharada', 'base_quantity' => 1, 'calories' => 64, 'protein' => .06, 'carbohydrates' => 17.30, 'fat' => 0],
            ['category' => 'carbohidratos', 'name' => 'Espagueti cocido', 'base_unit' => '150 g', 'base_quantity' => 150, 'calories' => 235, 'protein' => 8.64, 'carbohydrates' => 46.02, 'fat' => 1.38],
            ['category' => 'lacteos', 'name' => 'Requeson', 'base_unit' => '75 g', 'base_quantity' => 75, 'calories' => 90, 'protein' => 7.45, 'carbohydrates' => 2.32, 'fat' => 5.59],
            ['category' => 'verduras', 'name' => 'Espinacas', 'base_unit' => '30 g', 'base_quantity' => 30, 'calories' => 7, 'protein' => .86, 'carbohydrates' => 1.09, 'fat' => .12],
            ['category' => 'verduras', 'name' => 'Zanahoria', 'base_unit' => '50 g', 'base_quantity' => 50, 'calories' => 20, 'protein' => .46, 'carbohydrates' => 4.79, 'fat' => .12],
            ['category' => 'grasas', 'name' => 'Aceite de oliva', 'base_unit' => '1 cucharada', 'base_quantity' => 1, 'calories' => 119, 'protein' => 0, 'carbohydrates' => 0, 'fat' => 13.50],
            ['category' => 'frutas', 'name' => 'Mamey', 'base_unit' => '35 g', 'base_quantity' => 35, 'calories' => 18, 'protein' => .18, 'carbohydrates' => 4.38, 'fat' => .18],
            ['category' => 'frutas', 'name' => 'Mango', 'base_unit' => '85 g', 'base_quantity' => 85, 'calories' => 55, 'protein' => .43, 'carbohydrates' => 14.45, 'fat' => .23],
            ['category' => 'grasas', 'name' => 'Almendras', 'base_unit' => '10 piezas', 'base_quantity' => 10, 'calories' => 69, 'protein' => 2.55, 'carbohydrates' => 2.37, 'fat' => 6.08],
            ['category' => 'proteinas', 'name' => 'Pechuga de pollo', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 195, 'protein' => 29.55, 'carbohydrates' => 0, 'fat' => 7.72],
            ['category' => 'carbohidratos', 'name' => 'Arroz blanco cocido', 'base_unit' => '150 g', 'base_quantity' => 150, 'calories' => 194, 'protein' => 3.99, 'carbohydrates' => 41.85, 'fat' => .42],
            ['category' => 'carbohidratos', 'name' => 'Frijoles cocidos', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 151, 'protein' => 5.54, 'carbohydrates' => 21.39, 'fat' => 5.15],
            ['category' => 'grasas', 'name' => 'Aguacate', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 160, 'protein' => 2, 'carbohydrates' => 8.53, 'fat' => 14.66],
            ['category' => 'proteinas', 'name' => 'Tilapia', 'base_unit' => '200 g', 'base_quantity' => 200, 'calories' => 192, 'protein' => 40.16, 'carbohydrates' => 0, 'fat' => 3.40],
            ['category' => 'carbohidratos', 'name' => 'Papa cocida', 'base_unit' => '150 g', 'base_quantity' => 150, 'calories' => 120, 'protein' => 3.23, 'carbohydrates' => 27.33, 'fat' => .16],
            ['category' => 'verduras', 'name' => 'Pepino', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 15, 'protein' => .65, 'carbohydrates' => 3.63, 'fat' => .11],
            ['category' => 'proteinas', 'name' => 'Huevo entero', 'base_unit' => '1 pieza', 'base_quantity' => 1, 'calories' => 72, 'protein' => 6.30, 'carbohydrates' => .36, 'fat' => 4.80],
            ['category' => 'proteinas', 'name' => 'Claras de huevo', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 52, 'protein' => 10.90, 'carbohydrates' => .70, 'fat' => .20],
            ['category' => 'proteinas', 'name' => 'Atun en agua', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 116, 'protein' => 25.50, 'carbohydrates' => 0, 'fat' => .80],
            ['category' => 'proteinas', 'name' => 'Salmon', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 208, 'protein' => 20.40, 'carbohydrates' => 0, 'fat' => 13.40],
            ['category' => 'proteinas', 'name' => 'Carne molida 90/10', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 176, 'protein' => 20, 'carbohydrates' => 0, 'fat' => 10],
            ['category' => 'proteinas', 'name' => 'Bistec de res magro', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 187, 'protein' => 28, 'carbohydrates' => 0, 'fat' => 8],
            ['category' => 'proteinas', 'name' => 'Lomo de cerdo', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 143, 'protein' => 26, 'carbohydrates' => 0, 'fat' => 3.50],
            ['category' => 'proteinas', 'name' => 'Jamon de pavo', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 104, 'protein' => 17, 'carbohydrates' => 3, 'fat' => 2],
            ['category' => 'proteinas', 'name' => 'Camaron cocido', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 99, 'protein' => 24, 'carbohydrates' => .20, 'fat' => .30],
            ['category' => 'proteinas', 'name' => 'Sardina', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 208, 'protein' => 24.60, 'carbohydrates' => 0, 'fat' => 11.50],
            ['category' => 'proteinas', 'name' => 'Pierna de pollo sin piel', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 209, 'protein' => 26, 'carbohydrates' => 0, 'fat' => 10.90],
            ['category' => 'proteinas', 'name' => 'Muslo de pollo sin piel', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 177, 'protein' => 24, 'carbohydrates' => 0, 'fat' => 8],
            ['category' => 'proteinas', 'name' => 'Pechuga de pavo', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 135, 'protein' => 29, 'carbohydrates' => 0, 'fat' => 1],
            ['category' => 'proteinas', 'name' => 'Cecina de res', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 157, 'protein' => 31, 'carbohydrates' => 0, 'fat' => 3],
            ['category' => 'proteinas', 'name' => 'Arrachera', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 220, 'protein' => 24, 'carbohydrates' => 0, 'fat' => 13],
            ['category' => 'proteinas', 'name' => 'Filete de res', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 170, 'protein' => 26, 'carbohydrates' => 0, 'fat' => 7],
            ['category' => 'proteinas', 'name' => 'Milanesa de pollo', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 165, 'protein' => 31, 'carbohydrates' => 0, 'fat' => 3.60],
            ['category' => 'proteinas', 'name' => 'Tinga de pollo', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 150, 'protein' => 18, 'carbohydrates' => 4, 'fat' => 6],
            ['category' => 'proteinas', 'name' => 'Cochinita pibil', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 250, 'protein' => 18, 'carbohydrates' => 3, 'fat' => 18],
            ['category' => 'proteinas', 'name' => 'Carnitas maciza', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 290, 'protein' => 24, 'carbohydrates' => 0, 'fat' => 21],
            ['category' => 'proteinas', 'name' => 'Barbacoa de res', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 235, 'protein' => 28, 'carbohydrates' => 0, 'fat' => 13],
            ['category' => 'proteinas', 'name' => 'Lengua de res', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 224, 'protein' => 16, 'carbohydrates' => 0, 'fat' => 17],
            ['category' => 'proteinas', 'name' => 'Cazon', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 130, 'protein' => 26, 'carbohydrates' => 0, 'fat' => 2],
            ['category' => 'proteinas', 'name' => 'Huachinango', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 128, 'protein' => 26, 'carbohydrates' => 0, 'fat' => 2.70],
            ['category' => 'proteinas', 'name' => 'Mojarra', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 129, 'protein' => 26, 'carbohydrates' => 0, 'fat' => 2.70],
            ['category' => 'proteinas', 'name' => 'Bacalao', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 105, 'protein' => 23, 'carbohydrates' => 0, 'fat' => .90],
            ['category' => 'proteinas', 'name' => 'Pulpo cocido', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 164, 'protein' => 30, 'carbohydrates' => 4.40, 'fat' => 2.10],
            ['category' => 'proteinas', 'name' => 'Surimi', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 99, 'protein' => 15, 'carbohydrates' => 6.90, 'fat' => .90],
            ['category' => 'proteinas', 'name' => 'Tofu firme', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 144, 'protein' => 15.80, 'carbohydrates' => 3.90, 'fat' => 8.70],
            ['category' => 'proteinas', 'name' => 'Tempeh', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 193, 'protein' => 20.30, 'carbohydrates' => 7.60, 'fat' => 10.80],
            ['category' => 'proteinas', 'name' => 'Soya texturizada seca', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 336, 'protein' => 52, 'carbohydrates' => 33, 'fat' => 1],
            ['category' => 'proteinas', 'name' => 'Chorizo de pavo', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 150, 'protein' => 18, 'carbohydrates' => 2, 'fat' => 8],
            ['category' => 'lacteos', 'name' => 'Yogurt griego natural', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 59, 'protein' => 10, 'carbohydrates' => 3.60, 'fat' => .40],
            ['category' => 'lacteos', 'name' => 'Leche descremada', 'base_unit' => '250 ml', 'base_quantity' => 250, 'calories' => 86, 'protein' => 8.40, 'carbohydrates' => 12, 'fat' => .20],
            ['category' => 'lacteos', 'name' => 'Leche entera', 'base_unit' => '250 ml', 'base_quantity' => 250, 'calories' => 152, 'protein' => 7.90, 'carbohydrates' => 11.70, 'fat' => 8],
            ['category' => 'lacteos', 'name' => 'Queso panela', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 208, 'protein' => 18, 'carbohydrates' => 3, 'fat' => 14],
            ['category' => 'lacteos', 'name' => 'Queso cottage', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 98, 'protein' => 11.10, 'carbohydrates' => 3.40, 'fat' => 4.30],
            ['category' => 'carbohidratos', 'name' => 'Tortilla de maiz', 'base_unit' => '1 pieza', 'base_quantity' => 1, 'calories' => 52, 'protein' => 1.40, 'carbohydrates' => 10.70, 'fat' => .70],
            ['category' => 'carbohidratos', 'name' => 'Pan integral', 'base_unit' => '1 rebanada', 'base_quantity' => 1, 'calories' => 69, 'protein' => 3.60, 'carbohydrates' => 12, 'fat' => 1.10],
            ['category' => 'carbohidratos', 'name' => 'Camote cocido', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 86, 'protein' => 1.60, 'carbohydrates' => 20.10, 'fat' => .10],
            ['category' => 'carbohidratos', 'name' => 'Quinoa cocida', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 120, 'protein' => 4.40, 'carbohydrates' => 21.30, 'fat' => 1.90],
            ['category' => 'carbohidratos', 'name' => 'Lentejas cocidas', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 116, 'protein' => 9, 'carbohydrates' => 20.10, 'fat' => .40],
            ['category' => 'carbohidratos', 'name' => 'Garbanzos cocidos', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 164, 'protein' => 8.90, 'carbohydrates' => 27.40, 'fat' => 2.60],
            ['category' => 'carbohidratos', 'name' => 'Elote cocido', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 96, 'protein' => 3.40, 'carbohydrates' => 21, 'fat' => 1.50],
            ['category' => 'carbohidratos', 'name' => 'Granola', 'base_unit' => '30 g', 'base_quantity' => 30, 'calories' => 140, 'protein' => 3, 'carbohydrates' => 20, 'fat' => 5],
            ['category' => 'frutas', 'name' => 'Manzana', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 52, 'protein' => .30, 'carbohydrates' => 13.80, 'fat' => .20],
            ['category' => 'frutas', 'name' => 'Pera', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 57, 'protein' => .40, 'carbohydrates' => 15.20, 'fat' => .10],
            ['category' => 'frutas', 'name' => 'Naranja', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 47, 'protein' => .90, 'carbohydrates' => 11.80, 'fat' => .10],
            ['category' => 'frutas', 'name' => 'Papaya', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 43, 'protein' => .50, 'carbohydrates' => 10.80, 'fat' => .30],
            ['category' => 'frutas', 'name' => 'Sandia', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 30, 'protein' => .60, 'carbohydrates' => 7.60, 'fat' => .20],
            ['category' => 'frutas', 'name' => 'Pina', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 50, 'protein' => .50, 'carbohydrates' => 13.10, 'fat' => .10],
            ['category' => 'frutas', 'name' => 'Uvas', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 69, 'protein' => .70, 'carbohydrates' => 18.10, 'fat' => .20],
            ['category' => 'frutas', 'name' => 'Kiwi', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 61, 'protein' => 1.10, 'carbohydrates' => 14.70, 'fat' => .50],
            ['category' => 'frutas', 'name' => 'Melon', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 34, 'protein' => .80, 'carbohydrates' => 8.20, 'fat' => .20],
            ['category' => 'frutas', 'name' => 'Guayaba', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 68, 'protein' => 2.55, 'carbohydrates' => 14.32, 'fat' => .95],
            ['category' => 'frutas', 'name' => 'Tuna roja', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 41, 'protein' => .73, 'carbohydrates' => 9.57, 'fat' => .51],
            ['category' => 'frutas', 'name' => 'Tuna verde', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 41, 'protein' => .73, 'carbohydrates' => 9.57, 'fat' => .51],
            ['category' => 'frutas', 'name' => 'Granada', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 83, 'protein' => 1.67, 'carbohydrates' => 18.70, 'fat' => 1.17],
            ['category' => 'frutas', 'name' => 'Ciruela', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 46, 'protein' => .70, 'carbohydrates' => 11.40, 'fat' => .28],
            ['category' => 'frutas', 'name' => 'Durazno', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 39, 'protein' => .91, 'carbohydrates' => 9.54, 'fat' => .25],
            ['category' => 'frutas', 'name' => 'Nectarina', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 44, 'protein' => 1.06, 'carbohydrates' => 10.55, 'fat' => .32],
            ['category' => 'frutas', 'name' => 'Chabacano', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 48, 'protein' => 1.40, 'carbohydrates' => 11.12, 'fat' => .39],
            ['category' => 'frutas', 'name' => 'Mandarina', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 53, 'protein' => .81, 'carbohydrates' => 13.34, 'fat' => .31],
            ['category' => 'frutas', 'name' => 'Toronja', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 42, 'protein' => .77, 'carbohydrates' => 10.66, 'fat' => .14],
            ['category' => 'frutas', 'name' => 'Limon', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 29, 'protein' => 1.10, 'carbohydrates' => 9.32, 'fat' => .30],
            ['category' => 'frutas', 'name' => 'Lima', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 30, 'protein' => .70, 'carbohydrates' => 10.54, 'fat' => .20],
            ['category' => 'frutas', 'name' => 'Coco fresco', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 354, 'protein' => 3.33, 'carbohydrates' => 15.23, 'fat' => 33.49],
            ['category' => 'frutas', 'name' => 'Datil', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 282, 'protein' => 2.45, 'carbohydrates' => 75.03, 'fat' => .39],
            ['category' => 'frutas', 'name' => 'Higo', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 74, 'protein' => .75, 'carbohydrates' => 19.18, 'fat' => .30],
            ['category' => 'frutas', 'name' => 'Zapote negro', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 134, 'protein' => 1.40, 'carbohydrates' => 32, 'fat' => .40],
            ['category' => 'frutas', 'name' => 'Guanabana', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 66, 'protein' => 1, 'carbohydrates' => 16.84, 'fat' => .30],
            ['category' => 'frutas', 'name' => 'Maracuya', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 97, 'protein' => 2.20, 'carbohydrates' => 23.38, 'fat' => .70],
            ['category' => 'frutas', 'name' => 'Zarzamora', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 43, 'protein' => 1.39, 'carbohydrates' => 9.61, 'fat' => .49],
            ['category' => 'frutas', 'name' => 'Frambuesa', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 52, 'protein' => 1.20, 'carbohydrates' => 11.94, 'fat' => .65],
            ['category' => 'frutas', 'name' => 'Arandanos', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 57, 'protein' => .74, 'carbohydrates' => 14.49, 'fat' => .33],
            ['category' => 'frutas', 'name' => 'Cereza', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 63, 'protein' => 1.06, 'carbohydrates' => 16.01, 'fat' => .20],
            ['category' => 'frutas', 'name' => 'Tamarindo', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 239, 'protein' => 2.80, 'carbohydrates' => 62.50, 'fat' => .60],
            ['category' => 'frutas', 'name' => 'Tejocote', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 87, 'protein' => .80, 'carbohydrates' => 22, 'fat' => .20],
            ['category' => 'verduras', 'name' => 'Brocoli', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 35, 'protein' => 2.40, 'carbohydrates' => 7.20, 'fat' => .40],
            ['category' => 'verduras', 'name' => 'Calabacita', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 17, 'protein' => 1.20, 'carbohydrates' => 3.10, 'fat' => .30],
            ['category' => 'verduras', 'name' => 'Jitomate', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 18, 'protein' => .90, 'carbohydrates' => 3.90, 'fat' => .20],
            ['category' => 'verduras', 'name' => 'Lechuga', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 15, 'protein' => 1.40, 'carbohydrates' => 2.90, 'fat' => .20],
            ['category' => 'verduras', 'name' => 'Nopales', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 16, 'protein' => 1.30, 'carbohydrates' => 3.30, 'fat' => .10],
            ['category' => 'verduras', 'name' => 'Champinones', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 22, 'protein' => 3.10, 'carbohydrates' => 3.30, 'fat' => .30],
            ['category' => 'verduras', 'name' => 'Pimiento morron', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 31, 'protein' => 1, 'carbohydrates' => 6, 'fat' => .30],
            ['category' => 'verduras', 'name' => 'Coliflor', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 25, 'protein' => 1.90, 'carbohydrates' => 5, 'fat' => .30],
            ['category' => 'verduras', 'name' => 'Repollo', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 25, 'protein' => 1.30, 'carbohydrates' => 5.80, 'fat' => .10],
            ['category' => 'verduras', 'name' => 'Col morada', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 31, 'protein' => 1.40, 'carbohydrates' => 7.40, 'fat' => .20],
            ['category' => 'verduras', 'name' => 'Col de bruselas', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 43, 'protein' => 3.40, 'carbohydrates' => 9, 'fat' => .30],
            ['category' => 'verduras', 'name' => 'Kale', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 49, 'protein' => 4.30, 'carbohydrates' => 8.80, 'fat' => .90],
            ['category' => 'verduras', 'name' => 'Acelga', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 19, 'protein' => 1.80, 'carbohydrates' => 3.70, 'fat' => .20],
            ['category' => 'verduras', 'name' => 'Arugula', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 25, 'protein' => 2.60, 'carbohydrates' => 3.70, 'fat' => .70],
            ['category' => 'verduras', 'name' => 'Apio', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 16, 'protein' => .70, 'carbohydrates' => 3, 'fat' => .20],
            ['category' => 'verduras', 'name' => 'Cebolla blanca', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 40, 'protein' => 1.10, 'carbohydrates' => 9.30, 'fat' => .10],
            ['category' => 'verduras', 'name' => 'Cebolla morada', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 40, 'protein' => 1.10, 'carbohydrates' => 9.30, 'fat' => .10],
            ['category' => 'verduras', 'name' => 'Ajo', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 149, 'protein' => 6.40, 'carbohydrates' => 33.10, 'fat' => .50],
            ['category' => 'verduras', 'name' => 'Esparragos', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 20, 'protein' => 2.20, 'carbohydrates' => 3.90, 'fat' => .10],
            ['category' => 'verduras', 'name' => 'Ejotes', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 31, 'protein' => 1.80, 'carbohydrates' => 7, 'fat' => .20],
            ['category' => 'verduras', 'name' => 'Chicharos', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 81, 'protein' => 5.40, 'carbohydrates' => 14.50, 'fat' => .40],
            ['category' => 'verduras', 'name' => 'Betabel', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 43, 'protein' => 1.60, 'carbohydrates' => 9.60, 'fat' => .20],
            ['category' => 'verduras', 'name' => 'Rabano', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 16, 'protein' => .70, 'carbohydrates' => 3.40, 'fat' => .10],
            ['category' => 'verduras', 'name' => 'Berenjena', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 25, 'protein' => 1, 'carbohydrates' => 5.90, 'fat' => .20],
            ['category' => 'verduras', 'name' => 'Chayote', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 19, 'protein' => .80, 'carbohydrates' => 4.50, 'fat' => .10],
            ['category' => 'verduras', 'name' => 'Huauzontle', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 38, 'protein' => 4, 'carbohydrates' => 7, 'fat' => .60],
            ['category' => 'verduras', 'name' => 'Quelites', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 34, 'protein' => 3.20, 'carbohydrates' => 5.70, 'fat' => .70],
            ['category' => 'verduras', 'name' => 'Verdolagas', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 20, 'protein' => 2, 'carbohydrates' => 3.40, 'fat' => .40],
            ['category' => 'verduras', 'name' => 'Flor de calabaza', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 15, 'protein' => 1.20, 'carbohydrates' => 3.30, 'fat' => .20],
            ['category' => 'verduras', 'name' => 'Huitlacoche', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 58, 'protein' => 2.50, 'carbohydrates' => 12, 'fat' => 1],
            ['category' => 'verduras', 'name' => 'Tomatillo', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 32, 'protein' => 1, 'carbohydrates' => 5.80, 'fat' => 1],
            ['category' => 'verduras', 'name' => 'Chile poblano', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 29, 'protein' => 1.10, 'carbohydrates' => 6.70, 'fat' => .20],
            ['category' => 'verduras', 'name' => 'Chile serrano', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 32, 'protein' => 1.70, 'carbohydrates' => 6.70, 'fat' => .40],
            ['category' => 'verduras', 'name' => 'Chile jalapeno', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 29, 'protein' => .90, 'carbohydrates' => 6.50, 'fat' => .40],
            ['category' => 'verduras', 'name' => 'Alcachofa', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 47, 'protein' => 3.30, 'carbohydrates' => 10.50, 'fat' => .20],
            ['category' => 'verduras', 'name' => 'Poro', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 61, 'protein' => 1.50, 'carbohydrates' => 14.20, 'fat' => .30],
            ['category' => 'verduras', 'name' => 'Hinojo', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 31, 'protein' => 1.20, 'carbohydrates' => 7.30, 'fat' => .20],
            ['category' => 'verduras', 'name' => 'Jicama', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 38, 'protein' => .70, 'carbohydrates' => 8.80, 'fat' => .10],
            ['category' => 'verduras', 'name' => 'Germinado de alfalfa', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 23, 'protein' => 4, 'carbohydrates' => 2.10, 'fat' => .70],
            ['category' => 'verduras', 'name' => 'Germinado de soya', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 30, 'protein' => 3, 'carbohydrates' => 5.90, 'fat' => .20],
            ['category' => 'verduras', 'name' => 'Berros', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 11, 'protein' => 2.30, 'carbohydrates' => 1.30, 'fat' => .10],
            ['category' => 'verduras', 'name' => 'Endivia', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 17, 'protein' => 1.30, 'carbohydrates' => 3.40, 'fat' => .20],
            ['category' => 'verduras', 'name' => 'Rucula', 'base_unit' => '100 g', 'base_quantity' => 100, 'calories' => 25, 'protein' => 2.60, 'carbohydrates' => 3.70, 'fat' => .70],
            ['category' => 'grasas', 'name' => 'Nueces', 'base_unit' => '30 g', 'base_quantity' => 30, 'calories' => 196, 'protein' => 4.60, 'carbohydrates' => 4.10, 'fat' => 19.60],
            ['category' => 'grasas', 'name' => 'Crema de cacahuate', 'base_unit' => '1 cucharada', 'base_quantity' => 1, 'calories' => 94, 'protein' => 4, 'carbohydrates' => 3.20, 'fat' => 8],
            ['category' => 'grasas', 'name' => 'Semillas de chia', 'base_unit' => '15 g', 'base_quantity' => 15, 'calories' => 73, 'protein' => 2.50, 'carbohydrates' => 6.30, 'fat' => 4.60],
            ['category' => 'grasas', 'name' => 'Aceite de coco', 'base_unit' => '1 cucharada', 'base_quantity' => 1, 'calories' => 117, 'protein' => 0, 'carbohydrates' => 0, 'fat' => 13.60],
            ['category' => 'extras', 'name' => 'Cafe negro', 'base_unit' => '1 taza', 'base_quantity' => 1, 'calories' => 2, 'protein' => .30, 'carbohydrates' => 0, 'fat' => 0],
            ['category' => 'extras', 'name' => 'Chocolate amargo 70%', 'base_unit' => '20 g', 'base_quantity' => 20, 'calories' => 120, 'protein' => 1.60, 'carbohydrates' => 9, 'fat' => 8.50],
        ];

        foreach ($foods as $food) {
            $category = FoodCategory::where('slug', $food['category'])->firstOrFail();
            $slug = Str::slug($food['name']);

            Food::updateOrCreate(
                ['slug' => $slug],
                [
                    'food_category_id' => $category->id,
                    'name' => $food['name'],
                    'slug' => $slug,
                    'base_unit' => $food['base_unit'],
                    'base_quantity' => $food['base_quantity'],
                    'calories' => $food['calories'],
                    'protein' => $food['protein'],
                    'carbohydrates' => $food['carbohydrates'],
                    'fat' => $food['fat'],
                    'source' => 'manual',
                    'is_active' => true,
                ]
            );
        }
    }
}
